### ISSUE TITLE
fails to run 

### ISSUE THREAD

**Issue by hemna** [bhuman/VideoAnalysis#1]
I am trying to run the analysis against an mp4 video and it fails.

```
╭─VideoAnalysis on  main [?] via 🐍 v3.8.7 (.venv) took 4m49s ❯
└─> bin/analyze.py ~/mount/hpdev2-nfs-export/Soccer2023/Game8/REC_0001_overhead.MP4
    INFO: YOLOv5 🚀 torch 2.0.0 CPU

    INFO: Loading /Users/i530566/Desktop/Soccer games/test/VideoAnalysis/weights/best.mlmodel for CoreML inference...
Traceback (most recent call last):
  File "bin/analyze.py", line 82, in <module>
    cli()  # pylint: disable=no-value-for-parameter
  File "/Users/i530566/Desktop/Soccer games/test/VideoAnalysis/.venv/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/i530566/Desktop/Soccer games/test/VideoAnalysis/.venv/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/i530566/Desktop/Soccer games/test/VideoAnalysis/.venv/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/i530566/Desktop/Soccer games/test/VideoAnalysis/.venv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "bin/analyze.py", line 64, in cli
    analysis = VideoAnalysis(
  File "/Users/i530566/Desktop/Soccer games/test/VideoAnalysis/video_analysis/__init__.py", line 94, in __init__
    self._world_model = WorldModel(Camera(self._dataset.fps, self._settings), log, half == 2, field)
  File "/Users/i530566/Desktop/Soccer games/test/VideoAnalysis/video_analysis/world_model/__init__.py", line 38, in __init__
    self.game_state: GameState = GameState(log, snd_half)
  File "/Users/i530566/Desktop/Soccer games/test/VideoAnalysis/video_analysis/world_model/game_state.py", line 52, in __init__
    with open(log, encoding="UTF-8", newline="\n") as logfile:
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by roefer** [comment]
The syntax is

    bin/analyze.py --log /path/to/gamecontroller-log /path/to/video

So you need to specify a (pre-2023) GameController log to run the script.

**Comment by alkatar21** [comment]
The [option](https://github.com/bhuman/VideoAnalysis#options) is listed as a mandatory option. I have added this to the code as well.
